# Sử dụng biến môi trường động để Render tự động đồng bộ mạng nội bộ
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

# Cấu hình Hibernate tự động tạo bảng dữ liệu
spring.jpa.hibernate.ddl-auto=update

# Ép Hibernate nhận diện chính xác PostgreSQL
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect