spring.datasource.url=jdbc:postgresql://dpg-d80eccp194ac73bsvqt0-a-a.singapore-postgres.render.com:5432/rose_education_db?ssl=true
spring.datasource.username=rose_education_db_user
spring.datasource.password=hiPasVjxsHhi580RP9xlRieFiEIrXYS
spring.jpa.hibernate.ddl-auto=update
# 🌟 THÊM DÒNG NÀY ĐỂ ÉP HIBERNATE ĐỌC ĐÚNG ĐỊNH DẠNG POSTGRESQL
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect