# Chuỗi kết nối sử dụng External URL chuẩn xác của bạn
spring.datasource.url=jdbc:postgresql://dpg-d80eccp194ac73bsvqt0-a.singapore-postgres.render.com:5432/rose_education_db?ssl=true&sslmode=require
spring.datasource.username=rose_education_db_user
spring.datasource.password=hiPasVjxsHhi580RP9xlRieFiEIrXYS
spring.datasource.driver-class-name=org.postgresql.Driver

# Cấu hình Hibernate tự động đồng bộ bảng dữ liệu
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Định dạng ngôn ngữ dịch truy vấn PostgreSQL
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect